server:
  port: 50054
  timeout: 30s

database:
  host: localhost
  port: 5433
  user: postgres
  password: postgres
  dbname: bookings
  sslmode: disable
  max_connections: 100
  url: "pgx://postgres:postgres@localhost:5433/bookings?sslmode=disable"

kafka:
  brokers:
    - localhost:9092
  group_id: booking-service

logger:
  level: debug
  format: text

outbox:
  interval: 5s
  batch_size: 100